name = "Filadelfia Into the Villa-Verse"
author = "BanaMC"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ebfe337d2c50bbf4e4147190b637f4450fbe247672150aeda26c135b9f34529"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
