name = "Filadelfia Into the Villa-Verse"
author = "BanaMC"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb40b7ef8ba2dcca9565bf9c0558b2045f31ea4e309dcd1a1720390ea6297a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
