name = "Filadelfia Into the Villa-Verse"
author = "BanaMC"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29bc21b4beed45ce40b78495563800645cf0ab13bd34feac7854ba59aa3443cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
